In [2]:
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [67]:
def FindingPostsWithNegativeSentiments():
    df = pd.read_csv('../dataset/SO_Workflow_Data.csv')
    my_value = -1
    data = df.loc[df["RatingsGPTFineTuned"] == my_value]

    df = data[data['Body'].str.contains('teradata', case=False)] 
    print(len(df))
    df.to_csv('../dataset/teradata_posts.csv', index=False)

In [305]:
def MergeDF():
    # Merge df according to post id for getting the dates
    df1 = pd.read_csv('../dataset/WithAnswerDate.csv')
    df2 = pd.read_csv('../dataset/AssignedTopicGalaxy.csv')

    merged_df = pd.merge(df1, df2, on='Id')
    columns_to_include = ['Id', 'Title_x', 'Body_x', 'CreationDate', 'AcceptedAnswerDate', 'topic']

    # Create a new DataFrame with the selected columns
    df_new = merged_df[columns_to_include].copy()
    print(len(df_new))
    return df_new

In [306]:
def CalculateTimeComplexity(df):
    df = df.fillna('0001-01-01 00:00:00')
    df['time_interval'] = pd.Series(dtype=float)
    df['CreationDate'] = pd.to_datetime(df['CreationDate'])
    df['AcceptedAnswerDate'] = pd.to_datetime(df['AcceptedAnswerDate'], errors = 'coerce')
    df['time_interval'] = df['AcceptedAnswerDate'] - df['CreationDate'] 

    df['complexity'] = df['time_interval'].dt.days

    mean_time = []
    topic = [0,1, 2,3, 4,5,6,7,8,9]
    mean_time = []

    # print(df[df['topic']==5])
    for i in topic:
        topic_df = df[df['topic'] == i]

        if not topic_df.empty:
            if topic_df['complexity'].notna().any():
                mean = topic_df['complexity'].mean().round(2)
                mean_time.append(mean)
            else:
                mean_time.append(0)
    print(mean_time)
    
    # Create a line plot
    # fig = go.Figure()
    # colors = ['sandybrown', 'seagreen', 'seashell', 'sienna', 'silver',
    #         'skyblue', 'slateblue', 'slategray', 'slategrey', 'snow',
    #         'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato',
    #         'turquoise', 'violet', 'wheat', 'white', 'whitesmoke',
    #         'yellow', 'yellowgreen']

    # mode_size = [8, 8, 12, 8]
    # line_size = [2, 2, 4, 2]
    
    # # Add a line trace
    # fig.add_trace(go.Scatter(
    #     x=topic, y=mean_time,  
    #     mode='lines',
    #     line=dict(width=5),
    #     fill='tozeroy',
    #     fillcolor='seashell',
    #     line_color='indigo',
    #     connectgaps=True,
    #     showlegend=False))
    
    # fig.add_trace(go.Scatter(
    #     x=topic,
    #     y=mean_time,
    #     mode='markers+text',
    #     text=mean_time,
    #     textposition='top center',
    #     textfont={'family':'Balto', 'size':12},
    #     marker=dict(color='sandybrown', size=12)
    # ))

    # fig.update_layout(
    #     xaxis=dict(
    #         showline=True,
    #         showgrid=True,
    #         showticklabels=True,
    #         linecolor='rgb(204, 204, 204)',
    #         linewidth=2,
    #         ticks='outside',
    #         tickfont=dict(
    #             family='Arial',
    #             size=12,
    #             color='rgb(82, 82, 82)',
    #         )
    #     ),
    #     yaxis=dict(
    #         showgrid=True,
    #         zeroline=True,
    #         showline=True,
    #         showticklabels=True,
    #     ),
    #     autosize=False,
    #     margin=dict(
    #         autoexpand=False,
    #         l=100,
    #         r=20,
    #         t=115,
    #     ),
    #     showlegend=False,
    #     plot_bgcolor='white'
    # )

    # # Update layout to remove hovermode
    # fig.update_layout(hovermode=False)

    # # Set axis labels and plot title
    # fig.update_layout(title='Time Complexity For Each Topics In Kepler', xaxis_title='Topics', yaxis_title='Average Days')

    # # Show the plot
    # fig.show()


In [307]:
df = MergeDF()
CalculateTimeComplexity(df)

[0, 51.18, 266.0, 3.88, 0.0, 0, 5.0, 0.0, 0, 32.5]


/tmp/ipykernel_2755512/3237270425.py:5: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.



In [69]:
def MergeDFWithoutJoin():
    # Merge df according to post id for getting the dates
    df1 = pd.read_csv('../dataset/WithAnswerDate.csv')
    df2 = pd.read_csv('../dataset/AssignedTopicKnime.csv')

    merged_df = pd.merge(df1, df2, on='Id')
    columns_to_include = ['Id', 'Title_x', 'Body_x', 'CreationDate', 'AcceptedAnswerDate', 'topic']

    # Create a new DataFrame with the selected columns
    df_new = merged_df[columns_to_include].copy()
    df_new.to_csv('../result.csv')
    print(len(df_new))

def QuestionsWithoutAnswerPerTopic():
    df_new = pd.read_csv('../result.csv')\circled{0}
    df = df.fillna('0001-01-01 00:00:00')
    df['time_interval'] = pd.Series(dtype=float)
    df['CreationDate'] = pd.to_datetime(df['CreationDate'])
    df['AcceptedAnswerDate'] = pd.to_datetime(df['AcceptedAnswerDate'], errors = 'coerce')
    df['time_interval'] = df['AcceptedAnswerDate'] - df['CreationDate'] 

    df['complexity'] = df['time_interval'].dt.days

    mean_time = []
    topic = [0,1, 2,3, 4,5,6,7,8,9]
    mean_time = []

    # print(df[df['topic']==5])
    for i in topic:
        topic_df = df[df['topic'] == i]

        if not topic_df.empty:
            if topic_df['complexity'].notna().any():
                mean = topic_df['complexity'].mean().round(2)
                mean_time.append(mean)
                print('topic: ', i, 'time: ', mean)
            else:
                mean_time.append(0)
                
    print(mean_time)

MergeDFWithoutJoin()
# QuestionsWithoutAnswerPerTopic()
CalculateTimeComplexityWithoutPlots()

56
topic:  0 time:  13.9
topic:  3 time:  0.44
[13.9, 0, 0, 0.44, 0]


In [28]:
def ConcatMultipleDatasets():
    df = pd.read_csv('../dataset/SO_Workflow_Data.csv')
    data = df[df['RatingsGPTFineTuned'].isin([-1, 0])]
    df_galaxy = data[data['Body'].str.contains('galaxy', case=False)] 
    df_snakemake = data[data['Body'].str.contains('snakemake', case=False)] 
    df_knime = data[data['Body'].str.contains('knime', case=False)] 
    df_nextflow = data[data['Body'].str.contains('nextflow', case=False)] 
    df_kepler = data[data['Body'].str.contains('kepler', case=False)] 
    df_teradata = data[data['Body'].str.contains('teradata', case=False)] 
    df_airflow = data[data['Body'].str.contains('airflow', case=False)] 
    df_argo = data[data['Body'].str.contains('argo', case=False)] 
    df_luigi = data[data['Body'].str.contains('luigi', case=False)] 
    df_monetdb = data[data['Body'].str.contains('monetdb', case=False)] 
    df_rapidminer = data[data['Body'].str.contains('rapidminer', case=False)] 
    df_swarm = data[data['Body'].str.contains('swarm', case=False)] 
    df_workbench = data[data['Body'].str.contains('workbench', case=False)] 
    print(len(df_snakemake))

    frames = [df_galaxy, df_snakemake, df_knime, df_nextflow, df_kepler, df_teradata, df_airflow, df_argo, df_luigi, df_monetdb, df_rapidminer, df_swarm, df_workbench]

    result = pd.concat(frames)
    result.to_csv('../result.csv', index=False)
    print(len(result))

ConcatMultipleDatasets()

1188
5401


In [26]:
def CalculateSentiments():
    df = pd.read_csv('../dataset/13SystemsDataset.csv')
    print(df['RatingsGPTFineTuned'].value_counts())
    
CalculateSentiments()

RatingsGPTFineTuned
 0    3575
-1    1785
 1      41
Name: count, dtype: int64


In [13]:
def countRecordsPerYear():

    # Assuming df is your DataFrame and date_column is the column with datetime objects
    # If your datetime column is not already in datetime format, you can convert it using:
    # df['date_column'] = pd.to_datetime(df['date_column'])

    # Extract year from the datetime column
    df = pd.read_csv('../dataset/WithAnswerDate.csv')
    df['date_column'] = pd.to_datetime(df['CreationDate'])
    df['year'] = df['date_column'].dt.year

# Group by year and count the number of records
    records_per_year = df.groupby('year').size().reset_index(name='count')


    # Plotting
    # plt.figure(figsize=(10, 6))
    # records_per_year.plot(kind='line', marker='o', linestyle='-', color='b')
    # plt.title('Number of Records per Year')
    # plt.xlabel('Year')
    # plt.ylabel('Number of Records')
    # plt.grid(True)
    # plt.show()

    # fig = go.Figure()

    # fig.add_trace(go.Scatter(x=records_per_year['year'], y=records_per_year['count'],
    #                         mode='lines+markers', name='Records per Year', marker=dict(color='blue')))

    # fig.update_layout(title='Number of Records per Year',
    #                 xaxis=dict(title='Year'),
    #                 yaxis=dict(title='Number of Records'),
    #                 showlegend=True)

    # fig.show()
    fig = go.Figure()
    colors = ['sandybrown', 'seagreen', 'seashell', 'sienna', 'silver',
            'skyblue', 'slateblue', 'slategray', 'slategrey', 'snow',
            'springgreen', 'steelblue', 'tan', 'teal', 'thistle', 'tomato',
            'turquoise', 'violet', 'wheat', 'white', 'whitesmoke',
            'yellow', 'yellowgreen']

    mode_size = [8, 8, 12, 8]
    line_size = [2, 2, 4, 2]
    
    # Add a line trace
    fig.add_trace(go.Scatter(
        x=records_per_year['year'], y=records_per_year['count'],  
        mode='lines',
        line=dict(width=5),
        fill='tozeroy',
        fillcolor='seashell',
        line_color='indigo',
        connectgaps=True,
        showlegend=False))
    
    fig.add_trace(go.Scatter(
        x=records_per_year['year'],
        y=records_per_year['count'],
        mode='markers+text',
        text=records_per_year['count'],
        textposition='top left',
        textfont={'family':'Balto', 'size':12},
        marker=dict(color='sandybrown', size=12)
    ))

    fig.update_layout(
        xaxis=dict(
            showline=True,
            showgrid=True,
            showticklabels=True,
            linecolor='rgb(204, 204, 204)',
            linewidth=2,
            ticks='outside',
            tickfont=dict(
                family='Arial',
                size=12,
                color='rgb(82, 82, 82)',
            )
        ),
        yaxis=dict(
            showgrid=True,
            zeroline=True,
            showline=True,
            showticklabels=True,
        ),
        autosize=False,
        margin=dict(
            autoexpand=False,
            l=100,
            r=20,
            t=115,
        ),
        showlegend=False,
        plot_bgcolor='white'
    )

    # Update layout to remove hovermode
    fig.update_layout(hovermode=False)

    # Set axis labels and plot title
    fig.update_layout(title='Records Per Year', xaxis_title='Year', yaxis_title='Total Records')

    # Show the plot
    fig.show()


    

countRecordsPerYear()


In [15]:
import numpy as np
import pandas as pd
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer

# Example documents
df = pd.read_csv('../dataset/galaxy_posts.csv')
# my_value = -1
# new_df = df.loc[df["RatingsGPTFineTuned"] == my_value]
df["merged"] = df[["Body"]]
#new_df.head()
# new_df.to_csv('Dataset/ConcatenatedDatasetSO.csv')
print(len(df))
data = df.merged.values.tolist()
#data
# Remove Emails
data = [re.sub('<[^<>]*>', '', sent) for sent in data]
# Remove new line characters
data = [re.sub('\s+', ' ', sent) for sent in data]
# Remove distracting single quotes
data = [re.sub("\'", "", sent) for sent in data]

# pprint(data[:2])

# Vectorize the documents
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(data)

# Fit LDA model
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(X)

# Get topic assignments for each document
document_topics = lda.transform(X)

# Initialize topic co-occurrence matrix
co_occurrence_matrix = np.zeros((lda.n_components, lda.n_components))

# Update co-occurrence matrix based on topic assignments in documents
for doc_topics in document_topics:
    for i in range(len(doc_topics)):
        for j in range(i + 1, len(doc_topics)):
            co_occurrence_matrix[i, j] += 1

# Optionally, normalize the co-occurrence matrix
co_occurrence_matrix /= co_occurrence_matrix.sum(axis=1)[:, np.newaxis]

# Convert to a DataFrame for easier analysis or visualization
co_occurrence_df = pd.DataFrame(co_occurrence_matrix, columns=[f"Topic {i}" for i in range(lda.n_components)])
print(co_occurrence_df)


59
   Topic 0  Topic 1   Topic 2   Topic 3   Topic 4
0      0.0     0.25  0.250000  0.250000  0.250000
1      0.0     0.00  0.333333  0.333333  0.333333
2      0.0     0.00  0.000000  0.500000  0.500000
3      0.0     0.00  0.000000  0.000000  1.000000
4      NaN      NaN       NaN       NaN       NaN


/tmp/ipykernel_565939/2756913492.py:46: RuntimeWarning:

invalid value encountered in divide



In [22]:
import numpy as np

# Example data (replace this with your actual data)
topics = ["Topic1", "Topic2", "Topic3", "Topic4", "Topic5"]
systems = ["Galaxy", "SnakeMake", "Knime", "Nextflow", "Kepler", "Teradata", "Airflow", "Argo", "Luigi", "MonetDB", "RapidMiner", "Swarm", "Workbench"]

# Example: a dictionary indicating the presence or absence of each topic in each system
topic_data = {
    "Galaxy": [1, 1, 1, 1, 0],
    "SnakeMake": [0, 0, 1, 0, 1],
    "Knime": [1, 1, 0, 1, 0],
    "Nextflow": [1, 1, 1, 0, 0],
    "Kepler": [1, 1, 0, 0, 1],
    "Teradata": [1, 0, 0, 1, 0],
    "Airflow": [1, 1, 0, 0, 0],
    "Argo": [1, 1, 1, 0, 0],
    "Luigi": [1, 1, 1, 0, 0],
    "MonetDB": [1, 1, 0, 0, 0],
    "RapidMiner": [1, 0, 0, 0, 1],
    "Swarm": [1, 1, 0, 0, 0],
    "Workbench": [1, 0, 0, 0, 0]
    # ... (repeat for all systems)
}

# Convert the dictionary to a binary matrix
binary_matrix = np.array([topic_data[system] for system in systems])

# Calculate the co-occurrence matrix
co_occurrence_matrix = np.dot(binary_matrix.T, binary_matrix)

# Display the co-occurrence matrix
print("Co-Occurrence Matrix:")
print(co_occurrence_matrix)


Co-Occurrence Matrix:
[[12  9  4  3  2]
 [ 9  9  4  2  1]
 [ 4  4  5  1  1]
 [ 3  2  1  3  0]
 [ 2  1  1  0  3]]


In [23]:
# Example topics
topics = ["Error Handling and Resolution", "File Handling and Management", "Workflow Execution and Management", "Database Operations and Management", "Data Manipulation and Analysis"]

# Create a list of dictionaries to store the data
data_list = []

for i, source_topic in enumerate(topics):
    for j, target_topic in enumerate(topics):
        if i != j:  # Exclude diagonal elements
            data_list.append({
                "source": source_topic,
                "target": target_topic,
                "value": co_occurrence_matrix[i, j]
            })

# Convert the list of dictionaries to a DataFrame
co_occurrence_df = pd.DataFrame(data_list)

# Save the DataFrame to a CSV file
co_occurrence_df.to_csv("../co_occurrence_matrix.csv", index=False)

# Display the DataFrame
print("Co-Occurrence DataFrame:")
print(co_occurrence_df)

Co-Occurrence DataFrame:
                                source                              target  \
0        Error Handling and Resolution        File Handling and Management   
1        Error Handling and Resolution   Workflow Execution and Management   
2        Error Handling and Resolution  Database Operations and Management   
3        Error Handling and Resolution      Data Manipulation and Analysis   
4         File Handling and Management       Error Handling and Resolution   
5         File Handling and Management   Workflow Execution and Management   
6         File Handling and Management  Database Operations and Management   
7         File Handling and Management      Data Manipulation and Analysis   
8    Workflow Execution and Management       Error Handling and Resolution   
9    Workflow Execution and Management        File Handling and Management   
10   Workflow Execution and Management  Database Operations and Management   
11   Workflow Execution and Management 